In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

X = iris.data
y = iris.target

In [3]:
np.einsum('ij->j', X)

array([876.5, 458.6, 563.7, 179.9])

In [4]:
np.einsum('ij->i', X)

array([10.2,  9.5,  9.4,  9.4, 10.2, 11.4,  9.7, 10.1,  8.9,  9.6, 10.8,
       10. ,  9.3,  8.5, 11.2, 12. , 11. , 10.3, 11.5, 10.7, 10.7, 10.7,
        9.4, 10.6, 10.3,  9.8, 10.4, 10.4, 10.2,  9.7,  9.7, 10.7, 10.9,
       11.3,  9.7,  9.6, 10.5, 10. ,  8.9, 10.2, 10.1,  8.4,  9.1, 10.7,
       11.2,  9.5, 10.7,  9.4, 10.7,  9.9, 16.3, 15.6, 16.4, 13.1, 15.4,
       14.3, 15.9, 11.6, 15.4, 13.2, 11.5, 14.6, 13.2, 15.1, 13.4, 15.6,
       14.6, 13.6, 14.4, 13.1, 15.7, 14.2, 15.2, 14.8, 14.9, 15.4, 15.8,
       16.4, 14.9, 12.8, 12.8, 12.6, 13.6, 15.4, 14.4, 15.5, 16. , 14.3,
       14. , 13.3, 13.7, 15.1, 13.6, 11.6, 13.8, 14.1, 14.1, 14.7, 11.7,
       13.9, 18.1, 15.5, 18.1, 16.6, 17.5, 19.3, 13.6, 18.3, 16.8, 19.4,
       16.8, 16.3, 17.4, 15.2, 16.1, 17.2, 16.8, 20.4, 19.5, 14.7, 18.1,
       15.3, 19.2, 15.7, 17.8, 18.2, 15.6, 15.8, 16.9, 17.6, 18.2, 20.1,
       17. , 15.7, 15.7, 19.1, 17.7, 16.8, 15.6, 17.5, 17.8, 17.4, 15.5,
       18.2, 18.2, 17.2, 15.7, 16.7, 17.3, 15.8])

In [5]:
np.einsum('ij->', X)

2078.6999999999994

In [6]:
np.einsum('ij->ji', X)

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [8]:
X3D = np.stack([X[y == 0], X[y == 1], X[y == 2]], axis = 0)
X3D

array([[[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [9]:
X3D.shape

(3, 50, 4)

In [10]:
X3D_T = np.einsum('ijk->ikj', X3D)
X3D_T

array([[[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8,
         4.8, 4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1,
         4.8, 5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. ,
         5.5, 4.9, 4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6,
         5.3, 5. ],
        [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4,
         3. , 3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3,
         3.4, 3. , 3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2,
         3.5, 3.6, 3. , 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2,
         3.7, 3.3],
        [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6,
         1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7,
         1.9, 1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2,
         1.3, 1.4, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4,
         1.5, 1.4],
        [0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2,
         0.1, 0.1, 0.2, 0.4, 0.4, 0.3, 0.3,

In [13]:
T_3D = np.transpose(X3D, (0, 2, 1))
T_3D.shape

(3, 4, 50)

In [14]:
np.einsum('ij,kj->ik', X, X)

array([[40.26, 37.49, 37.03, ..., 51.33, 51.54, 48.09],
       [37.49, 35.01, 34.49, ..., 48.53, 48.6 , 45.41],
       [37.03, 34.49, 34.06, ..., 47.31, 47.5 , 44.32],
       ...,
       [51.33, 48.53, 47.31, ..., 82.29, 83.18, 77.47],
       [51.54, 48.6 , 47.5 , ..., 83.18, 84.45, 78.46],
       [48.09, 45.41, 44.32, ..., 77.47, 78.46, 73.06]])

In [15]:
G = np.einsum('ij,ik->jk', X, X)

In [16]:
G_3D = np.einsum('ijk,ijm->ikm', X3D, X3D)
G_3D

array([[[1259.09,  862.89,  366.74,   62.08],
        [ 862.89,  594.6 ,  251.16,   42.62],
        [ 366.74,  251.16,  108.35,   18.28],
        [  62.08,   42.62,   18.28,    3.57]],

       [[1774.86,  826.31, 1273.33,  396.29],
        [ 826.31,  388.47,  594.06,  185.67],
        [1273.33,  594.06,  918.2 ,  286.02],
        [ 396.29,  185.67,  286.02,   89.83]],

       [[2189.9 ,  984.23, 1843.69,  669.77],
        [ 984.23,  447.33,  829.08,  303.6 ],
        [1843.69,  829.08, 1556.16,  564.81],
        [ 669.77,  303.6 ,  564.81,  208.93]]])

In [17]:
a_1D = X[0]
b_1D = X[1]

In [18]:
np.einsum('i->',a_1D)

10.2

In [20]:
print(np.einsum('i,i->i',a_1D,b_1D))

[24.99 10.5   1.96  0.04]


In [21]:
print(np.einsum('i,i->',a_1D,b_1D))

37.489999999999995


In [22]:
print(np.einsum('i,j->ij',a_1D,b_1D))

[[24.99 15.3   7.14  1.02]
 [17.15 10.5   4.9   0.7 ]
 [ 6.86  4.2   1.96  0.28]
 [ 0.98  0.6   0.28  0.04]]


In [23]:
np.einsum('ii->i',G)

array([5223.85, 1430.4 , 2582.71,  302.33])

In [24]:
np.diag(G)

array([5223.85, 1430.4 , 2582.71,  302.33])

In [25]:
np.einsum('ii->',G)

9539.289999999997

In [26]:
n = X.shape[0]  # 样本数量
mean_X = np.einsum('ij->j', X) / n

In [27]:
mean_X

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [28]:
X_c = X - mean_X  # 中心化数据
variance = np.einsum('ij,ij->j', X_c, X_c) / (n - 1)

In [29]:
variance

array([0.68569351, 0.18997942, 3.11627785, 0.58100626])

In [30]:
cov_matrix = np.einsum('ij,ik->jk', X_c, X_c) / (n - 1)

In [31]:
cov_matrix

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [32]:
np.cov(X.T, ddof = 1)

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [33]:
X3D_mean = np.mean(X3D, axis = 1)
X3D_mean

array([[5.006, 3.428, 1.462, 0.246],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]])